In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv('titanic_train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [5]:
df.dropna(inplace=True)

In [6]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [7]:

df['family'] = df['SibSp'] + df['Parch']

In [9]:
df.drop(['SibSp','Parch'],axis=1,inplace=True)

In [10]:
df.head()

    Age     Fare  Survived  family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [11]:
X=df.drop('Survived',axis=1)
y=df['Survived']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
X_test.head()

      Age   Fare  family
149  42.0  13.00       0
407   3.0  18.75       2
53   29.0  26.00       1
369  24.0  69.30       0
818  43.0   6.45       0

In [14]:
clf=DecisionTreeClassifier(random_state=42)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
accuracy_score(y_test,y_pred)
print("Accuracy:", round(accuracy_score(y_test,y_pred)*100,2),"%")

Accuracy: 62.24 %

In [15]:
from sklearn.preprocessing import Binarizer

In [18]:
trf=ColumnTransformer([
    ('binarizer',Binarizer(threshold=0,copy=False),['family'])
],remainder='passthrough')

In [19]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.transform(X_test)

clf=DecisionTreeClassifier(random_state=42)
clf.fit(X_train_trf,y_train)
y_pred1=clf.predict(X_test_trf)
accuracy_score(y_test,y_pred1)
print("Accuracy after Binarization:", round(accuracy_score(y_test,y_pred1)*100,2),"%")

Accuracy after Binarization: 64.34 %

In [22]:
X_trf=trf.transform(X)
cross_val_score(clf,X_trf,y,cv=5).mean()
print("Accuracy after cross validation of the binarization:", round(cross_val_score(clf,X_trf,y,cv=5).mean()*100,2),"%")

Accuracy after cross validation of the binarization: 61.91 %